### ISSUE TITLE
Image preview open file dialog?

### ISSUE THREAD

**Issue by orschiro** [flathub/com.slack.Slack#10]
Hey guys, 

Really great having this flatpak! :-)

But not having an image preview in the open file dialog is kind of a bumper.

Can we somehow enable that?

Thanks!

Robert

![screenshot from 2018-02-20 17-00-03](https://user-images.githubusercontent.com/170947/36436520-c3594782-1664-11e8-9565-ab95eddc347a.png)

**Comment by nedrichards** [comment]
This is an issue with the GTK2 file chooser I believe. Electron is still linking against GTK2 rather than GTK3. Chromium has just made the switch to GTK3, so I expect electron to eventually pick this up and then Slack to upgrade appropriately. Might take a little while though.

Thanks for the report though! Really glad you're liking the flatpak.

**Comment by orschiro** [comment]
@nedrichards thanks for explaining! Now I understand how it works. :-) 

Cool, patiently waiting now...

do you have the upstream Electron issue on that for me to follow too?

**Comment by TingPing** [comment]
Upstream Electron is already on Gtk3, just need the application to upgrade.

**Comment by orschiro** [comment]
@TingPing awesome news! 

> , just need the application to upgrade.

You mean this application?

**Comment by TingPing** [comment]
Yes.
