### ISSUE TITLE
Unable to upload files from home directory

### ISSUE THREAD

**Issue by lentzi90** [flathub/com.slack.Slack#46]
The current [sandbox permissions](https://github.com/flathub/com.slack.Slack/blob/master/com.slack.Slack.json#L16) does not include `home`, which means that it is impossible to upload files from say `~/workspace`. Only specific folders like `Documents` or `Downloads` are included in the permissions right now.

**Expected:** That I can upload a file from `~/workspace`.

**Actual:** Uploading fails with a message about the file type not being supported. If I move the file to `~/Documents` and retry, it works without problem.
This is for drag and drop. If you instead try to use the file chooser, you won't be able to see or open all folders, only those currently covered in the filesystem sandbox permissions.

**Suggested change:**
I suggest that we replace
```
"--filesystem=xdg-documents:ro",
"--filesystem=xdg-pictures:ro",
"--filesystem=xdg-music:ro",
"--filesystem=xdg-videos:ro",
```
with
```
"--filesystem=home:ro",
```
or simply add it to the current list.

**Comment by FakeShemp** [comment]
This is the intended behavior unfortunately. Having home access is a bit more dangerous than specific portals to the XDG directories.

If you absolutely need `~/` access, I would say it's recommended for advanced users to just run `flatpak run --filesystem=home:ro com.slack.Slack` instead. Or you can make it permanent on your system by using `sudo flatpak override --filesystem=home:ro com.slack.Slack`. You probably know what you're doing in that case :)

**Comment by FakeShemp** [comment]
However, I've added a notification in the readme on github for anyone who runs into the same issue.

https://github.com/flathub/com.slack.Slack/pull/47

**Comment by lentzi90** [comment]
I see, thanks for the info

**Comment by Gadgetoid** [comment]
I feel it's worth noting that this breaks what I would expect to be normal drag-and-drop file sharing behaviour in completely confusing and unexpected ways and presents the paradox of requiring advanced knowledge to enable a basic everyday feature.

Case in point:
1. I have a folder in my home directory from which I want to share a file.
2. I drag and drop that file into Slack
3. Instead of getting a "Slack does not have permission to access this directory" I see "File unsupported", "Sorry, test.png is a type of file not supported by Slack", "Try uploading a .zip version of this file instead.":
![image](https://user-images.githubusercontent.com/1746967/105249270-c5070080-5b6f-11eb-949c-d1b4b1fe7b56.png)
4. I zip the file... GOTO 3
5. The penny drops that this will be one of *those* problems, and since I am an "advanced" user I hit Google, find this post, run the magic incantation and... it works.

I don't know if I expect you to *do* anything about it, but hopefully at least this comment will help lead anyone encountering this same baffling mystery to the same fix.

**Comment by carlocastoldi** [comment]
Can we either keep this issue open or put the README back up?
This is a frequent problem.

**Comment by FedericoCapaldo** [comment]
I have same issue as @Gadgetoid

**Comment by kleinschmidt** [comment]
I was confused by this for so long until I remembered that I installed slack with flatpak.....

**Comment by Hoeze** [comment]
Why can't we just have a "ask user for permission" dialog in that case?

**Comment by FakeShemp** [comment]
@Hoeze because we are not the developers of slack.

**Comment by Hoeze** [comment]
@FakeShemp I mean as I understand this is a permission issue with Flatpak, right?
Slack tries to access `~/` but fails because the Flatpak sandbox denies the request.
Why not let Flatpak open a dialog: "Do you want to allow `com.slack.Slack` to access `~/...`"?

Please excuse me if that's a dumb question, I'm not familiar with Flatpak from a dev's perspective :)

**Comment by Benzer1406** [comment]
I installed Slack from the snap store with `sudo snap install slack` and I could drag'n'drop from any directory.

**Comment by nerijus** [comment]
This github repo is about flatpak, not snap.

**Comment by dreua** [comment]
@FakeShemp could you put the readme back up or at least pin this issue? Ideally that would be noted on the [flathub page](https://flathub.org/apps/details/com.slack.Slack) as well. Regular users will never understand this on their own, even me, maintainer of a small flatpak, forgot about this and wasted some time do figure it out.

Is there a way to report this to Slack? They should at least fix their error message imo. Using File Portals would be the ideal solution.

**Comment by jbarlow83** [comment]
Since running Slack from the command line is not a good solution, you can use Flatseal to grant it these permissions.
![image](https://github.com/flathub/com.slack.Slack/assets/1825843/04eb444d-5449-4b37-9505-cc1f7bd8db98)

After changing permissions, you will have quit Slack and ensure it's been quick from the notification area/system tray/whatever as well, for this to take effect.

It really would be better to have an explanation on the Flathub page or disable sandboxing.

**Comment by dreua** [comment]
The best solution would be using file portals but until then at least change the ridiculous hint to zip it.

**Comment by merschformann** [comment]
Thank you for the pointers @jbarlow83 ! Worked like a charm for me. :hugs:

**Comment by dreua** [comment]
@sztomi I don't think this is wort reasoning about, in the average home directory there will be enough sensitive data that full file system access doesn't really make a difference IMO. Furthermore the Unix access restrictions will still apply and the flatpak hides or overlays some stuff even with full access. Users may run into problems again if they try to share files from USB drives or network mounts.

**Comment by dreua** [comment]
@jramsey-ctg Install flatseal and change the permissions, nothing is restricting you.

**Comment by cassidyjames** [comment]
This issue was raised to Endless by a user.

Is my understanding correct that this is only still an issue because Slack (upstream, proprietary) is using an old version of Electron that still does not implement file portals, or are they doing something even more wrong here?

My understanding was that the file picker and drag-and-drop should just work with recent versions of Electron, but I could be wrong.
